
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
 # For extra security set this to only accept connections on localhost if NGINX is on the same machine
 # server_host: 127.0.0.1
 # Update this line to be your domain
 base_url: https://sam.grashorntech.com
 use_x_forwarded_for: true
 # You must set the trusted proxy IP address so that Home Assistant will properly accept connections
 # Set this to your NGINX machine IP, or localhost if hosted on the same machine.
 trusted_proxies: 127.0.0.1
history:
    include:
        entities:
            - switch.porch_lights

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automation.yaml
script: !include scripts.yaml
light: !include lights.yaml

cover:
  - platform: myq
    username: sjkreuze@gmail.com
    password: lHgxq6GVUH3DfGiT7gWC
    type: chamberlain

zwave: !include zwave.yaml
